# Generated by Django 2.2.6 on 2019-11-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a source which articles are published', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a type of article topic', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('date_of_publish', models.DateField()),
                ('url', models.URLField(help_text='Enter a url that links to the article.', max_length=1000)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Online_Content.Author')),
                ('source', models.ForeignKey(help_text='Select a source for this article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Online_Content.Source')),
                ('topic', models.ForeignKey(help_text='Select a topic for this article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Online_Content.Topic')),
            ],
        ),
    ]
