# Generated by Django 2.2.6 on 2019-11-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
