# Generated by Django 2.2.6 on 2019-11-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Content', '0003_auto_20191122_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
