# Generated by Django 2.2.6 on 2019-11-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Content', '0005_auto_20191122_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_content',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Online_Content.Article', unique=True)),
                ('content', models.TextField(help_text='Enter the full content for the article.')),
            ],
        ),
    ]
