# Generated by Django 2.2.6 on 2019-11-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Content', '0006_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_of_publish']},
        ),
    ]
