# Generated by Django 2.2.6 on 2019-11-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Content', '0008_auto_20191125_1705'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article_content',
            managers=[
            ],
        ),
    ]
